version: "3.9"

services:
  backend:
    container_name: datsmysong-backend
    build: .
    ports:
      - "8182:3000"
    env_file:
      - .backend.production.env
    restart: always

networks:
  default:
    name: datsmysong
    external: true
