@startuml
!theme plain
left to right direction

title Paramétrer la salle d’écoute

:Hôte: as H

package app{
	usecase (Configurer la possibilité de voter pour passer une musique) as TOGGLE_VOTE
    usecase (Configurer le pourcentage de votes nécessaires pour passer la musique actuelle) as CONFIG_VOTE_PERCENTAGE
	usecase (Configurer le nombre maximum de musiques qu’un seul et même participant peut ajouter à la fois) as CONFIG_NB_MUSIC
	usecase (Configurer le nombre maximum de musiques en file d’attente à un instant T) as CONFIG_NB_MUSIC_PER_PARTICIPANT
	usecase (Configurer le nombre maximal de participants pouvant rejoindre la salle d’écoute) as CONFIG_NB_PARTICIPANT_MAX
	usecase (Configurer la durée maximale d’une musique pouvant être ajoutée en file d’attente) as CONFIG_MAX_DURATION_PER_MUSIC
}

H -- TOGGLE_VOTE
H -- CONFIG_VOTE_PERCENTAGE
H -- CONFIG_NB_MUSIC
H -- CONFIG_NB_MUSIC_PER_PARTICIPANT
H -- CONFIG_NB_PARTICIPANT_MAX
H -- CONFIG_MAX_DURATION_PER_MUSIC
@enduml