@startuml
!theme plain
left to right direction

title Gérer/créer son compte

:Visiteur: as V
:Utilisateur: as U

package app{

  usecase (Lier son compte de streaming) as LINK_STREAMING_ACCOUNT
  usecase (Consulter son profil) as VIEW_PROFILE
  usecase (Créer un compte) as CREATE_ACCOUNT
  usecase (Regarder sa liste d’amis et la gérer) as FRIENDS
  usecase (Consulter les salles d’écoutes dans lesquelles il a participé) as HISTORY
  usecase (Regarder les détails d’une salle d’écoute dans laquelle il a participé) as HISTORY_DETAILS
}

V -- CREATE_ACCOUNT

U -- VIEW_PROFILE
U -- FRIENDS
U -- LINK_STREAMING_ACCOUNT
U -- HISTORY

HISTORY <.. "<<extends>>" HISTORY_DETAILS
@enduml