@startuml
!theme plain
left to right direction

title Diagramme général

:Visiteur: as V
:Utilisateur: as U
:Participant: as P
:Participant anonyme: as PA
:Hôte: as H

package app{

  usecase (Rejoindre une salle d'écoute) as JOIN_ROOM
  usecase (Créer une salle d'écoute) as CREATE_ROOM
  usecase (Gérer son compte) as MANAGE_ACCOUNT
  usecase (Créer son compte) as CREATE_ACCOUNT

  usecase (Intéragir avec la salle d'écoute) as SALLE
  usecase (Paramétrer la salle d’écoute) as PARAMETER

}

V -- JOIN_ROOM
V -- CREATE_ACCOUNT

U -- MANAGE_ACCOUNT
U -- JOIN_ROOM
U -- CREATE_ROOM

P <|-- PA
P -- SALLE

H -- PARAMETER
H -- SALLE
@enduml