@startuml
!theme aws-orange

title Use Case Diagram 

:Utilisateur (non connecté): as UNC
:Utilisateur (connecté): as UC

package app{
  usecase (Créer un  compte via Google) as CG
  usecase (Créer un compte via Spotify / Apple music) as CSA
  usecase (Créer un compte via un mail et un mot de passe) as CM
  usecase (Rejoindre une salle d’écoute via un lien) as JOIN
  usecase (Créer une salle d’écoute) as CREATE
  usecase (Lier son compte Spotify / Apple Music) as LIER
  usecase (Changer son nom d’utilisateur) as CHANGE
  usecase (Regarder l’historique des salles d’écoutes dans lesquels il a participé) as HISTORY
  usecase (Regarder les détails d’une salle d’écoute dans laquelle il a participé) as DETAILS
  usecase (Regarder sa liste d’amis) as FRIENDSLIST
  usecase (Ajouter un ami) as ADDFRIEND
  
}

UNC -- CG
UNC -- CSA
UNC -- CM
UNC -- JOIN

UC -- CREATE
CREATE ..> "<<include>>" CSA
CREATE ..> "<<include>>" LIER
UC -- JOIN
UC -- CHANGE
UC -- HISTORY
HISTORY ..> "<<extends>>" DETAILS
UC -- FRIENDSLIST
FRIENDSLIST ..> "<<extends>>" ADDFRIEND



@enduml