@startuml Diagramme de classe

!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define primary_key(x) <b>x</b>
!define foreign_key(x) <u>#x</u>
!define int_field(x) x : INT
!define text_field(x) x : TEXT
!define bucket(x) x : BUCKET
!define or_null(x) x : NULL
!define boolean_field(x) x : BOOLEAN
!define date_field(x) x : DATE

Table(Profile, "profile") {
    int_field(primary_key(profile_id))
    text_field(nickname)
    date_field(created_at)
}

Table(RoomConfig, "rooms_configuration"){
    int_field(primary_key(id))
    boolean_field(vote_skipping)
    int_field(vote_skipping_needed_percentage)
    int_field(max_music_count_in_queue_per_user)
    int_field(max_music_duration)
}

Table(ActiveRoom, "active_rooms"){
    int_field(primary_key(id))
    text_field(name)
    text_field(code)
    int_field(foreign_key(configuration_id))
    int_field(foreign_key(host_user_profile_id))
    date_field(created_at)
    int_field(int_field(foreign_key(service_id)))
}

Table(Rooms, "rooms") {
    int_field(primary_key(id))
    text_field(name)
    date_field(created_at)
    date_field(ended_at)
    int_field(foreign_key(configuration_id))
    int_field(foreign_key(host_user_profile_id))
    int_field(foreign_key(service_id))
}

Table(RoomUsers, "room_users") {
    int_field(primary_key(foreign_key(room_id)))
    text_field(primary_key(foreign_key(profile_id)))
    boolean_field(banned)
    date_field(joined_at)
}

Table(FriendList, "friends_list"){
    int_field(primary_key(foreign_key(user_profile1_id)))
    int_field(primary_key(foreign_key(user_profile2_id)))
    date_field(friends_since)
}

Table(FriendsRequest, "friends_request"){
    int_field(primary_key(foreign_key(asker_user_profile_id)))
    int_field(primary_key(foreign_key(receiver_user_profile_id)))
    date_field(sent_at)
    date_field(expires_at)
}

Table(StreamingService, "streaming_services"){
    int_field(primary_key(service_id))
    text_field(serviceName)
    text_field(image_url)
}

Table(BoundServices, "bound_services"){
    int_field(primary_key(foreign_key(service_id)))
    int_field(primary_key(foreign_key(user_profile_id)))
    text_field(access_token)
    text_field(refresh_token)
    date_field(expires_in)
}

Table(UserProfile, "user_profile"){
    int_field(primary_key(user_profile_id))
    int_field(foreign_key(user_id))
    int_field(foreign_key(profile_id))
    text_field(username)
    avatar : AVATAR
}

Table(RoomHistory, "room_history"){
    int_field(primary_key(history_id))
    int_field(foreign_key(room_id))
    text_field(music_id)
    int_field(position)
}

Profile "0" -- "1" RoomUsers : profile_id
UserProfile "1" -- "*" FriendList : user_profile_id_1
UserProfile "1" -- "*" FriendList : user_profile_id_2
UserProfile "1" -- "*" FriendsRequest : asker_user_profile_id
UserProfile "1" -- "*" FriendsRequest : receiver_user_profile_id
RoomConfig "1" -- "*" ActiveRoom : configuration_id
UserProfile "1" -- "*" ActiveRoom : host_user_profile_id
StreamingService "1" -- "*" ActiveRoom : service_id
RoomConfig "1" -- "*" Rooms : configuration_id
Rooms "1" -- "*" UserProfile : "host_user_profile_id"
StreamingService "1" -- "*" Rooms : service_id
UserProfile "1" -- "*" BoundServices : user_profile_id
StreamingService "1" -- "*" BoundServices : service_id
RoomHistory "*" -- "1" Rooms : room_id
Profile "1" -- "*" UserProfile : user_profile_id
@enduml